export const ROUTES = {
  HOME: "/",
  HOME_COURSES: "/home_courses",
  ABOUT: "/about",
  BLOG: "/blog",
  BLOGDETAILS: "/blog/:id",
  TEACHERS: "/teachers",
  GRADUATES: "/graduates",
  CONTACT: "/contact",
  COURSES: "/courses",
  CORPORATE: "/corporate",
  COURSEDETAILS: "/courses/:id",
  SERVICES: "/services",
  CONSULTATION: "/consultation",
  FAQ: "/faq",
  NETWORKING: "/networking",
  AGENCY: {
    CONTACT: "/agency/contact",
    APPLY: "/agency/apply",
    ABOUT: "/agency/about",
    INTERN: "/agency/intern",
    PRODUCT: "/agency/product",
    PROJECT: "/agency/project",
    SEARCH: "/agency/search",
    SERVICE: "/agency/service",
    PRODUCT: "/agency/product",
    PROJECTDETAIL: "/project/:id",
    SERVICEDETAIL: "/service/:id",
  },
};
